// 16x16 pixel-art item icons (grids + palette swaps), cached as canvases.

import { makeCanvas } from '../engine/gfx.js';
import { ramp } from '../engine/color.js';
import { ITEMS } from '../data/items.js';

const S = {
  fish: [
    '................',
    '................',
    '................',
    '.......oo.......',
    '......odmo......',
    '.oo..ommmmoo....',
    'odmooommmmmmoo..',
    'odmmmmmmmmmwkmo.',
    'odmmmmmmmmmmmmmo',
    'odmoolllllllmo..',
    '.oo..oolllloo...',
    '......oddo......',
    '.......oo.......',
    '................',
    '................',
    '................',
  ],
  crab: [
    '................',
    '..oo........oo..',
    '.omlo......olmo.',
    '.ommo......ommo.',
    '..oo.o....o.oo..',
    '.....k.oo.k.....',
    '...oommmmmmoo...',
    '..ommmlllmmmmo..',
    '.ommmmmmmmmmmmo.',
    '.odmmmmmmmmmmdo.',
    '..oddddddddddo..',
    '.o.o.o....o.o.o.',
    'o..o..o..o..o..o',
    '................',
    '................',
    '................',
  ],
  puffer: [
    '................',
    '......o..o......',
    '...o.oooooo.o...',
    '....ommmmmmo....',
    '.o.omlmmmmmmo.o.',
    '..ommmmmmmwkmo..',
    'oomlmmmmmmkkmmo.',
    '.ommmmmmmmmmmoo.',
    '.ommlllllllmmo..',
    'oodllllllllldoo.',
    '..odlllllllldo..',
    '.o.odddddddo.o..',
    '....o.oooo.o....',
    '................',
    '................',
    '................',
  ],
  boot: [
    '................',
    '................',
    '.....oooooo.....',
    '.....ommmmo.....',
    '.....omlmmo.....',
    '.....ommmmo.....',
    '.....ommmmo.....',
    '.....ommmmoo....',
    '.....ommmmmmoo..',
    '.....ommmmmmmmo.',
    '.....ommlmmmmmo.',
    '.....odddddddddo',
    '.....ooooooooooo',
    '....w...w.......',
    '................',
    '................',
  ],
  seaweed: [
    '................',
    '........o.......',
    '.......omo......',
    '...o...omo..o...',
    '..omo..omo.omo..',
    '..omo.omo..omo..',
    '...omoomo.omo...',
    '...omomo..omo...',
    '....ommo.omo....',
    '....omlmomo.....',
    '.....ommmo......',
    '.....omdmo......',
    '....oommmoo.....',
    '...odddddddo....',
    '....ooooooo.....',
    '................',
  ],
  berry: [
    '................',
    '.........oo.....',
    '........oggo....',
    '.......ogo......',
    '....ooo.oooo....',
    '...ommmoomlmo...',
    '..omlmmmommmmo..',
    '..ommmmoommmmo..',
    '..odmmmommmdmo..',
    '...ooooommdmo...',
    '...omlmmoooo....',
    '..ommmmmmo......',
    '..odmmmmdo......',
    '...oddddo.......',
    '....oooo........',
    '................',
  ],
  apple: [
    '................',
    '........o.......',
    '.......oko..oo..',
    '........ko.ogo..',
    '.....oooooogo...',
    '....ommmmmmoo...',
    '...omlwmmmmmmo..',
    '...omlmmmmmmmo..',
    '...ommmmmmmmmo..',
    '...ommmmmmmmdo..',
    '...ommmmmmmmdo..',
    '....ommmmmmddo..',
    '....oddmmmddo...',
    '.....ooddddoo...',
    '.......oooo.....',
    '................',
  ],
  mushroom: [
    '................',
    '................',
    '.....oooooo.....',
    '...oommmmwmoo...',
    '..ommwwmmmmmmo..',
    '.ommmmmmmmwwmmo.',
    '.omwwmmmmmmmmmo.',
    '.oddddddddddddo.',
    '..ooollllllooo..',
    '.....ollllo.....',
    '.....ollllo.....',
    '.....olllwo.....',
    '....ollllllo....',
    '....oddddddo....',
    '.....oooooo.....',
    '................',
  ],
  shell: [
    '................',
    '................',
    '................',
    '.......oo.......',
    '.....oommoo.....',
    '....omlmlmlmo...',
    '...omlmlmlmlmo..',
    '..omlmlmlmlmlmo.',
    '..omlmlmlmlmlmo.',
    '..odmdmdmdmdmdo.',
    '...ooooooooooo..',
    '......odddo.....',
    '.......ooo......',
    '................',
    '................',
    '................',
  ],
  glass: [
    '................',
    '................',
    '................',
    '......oooo......',
    '....oollmmoo....',
    '...olwlmmmmmo...',
    '..olwlmmmmmmmo..',
    '..ollmmmmmmmmo..',
    '..ommmmmmmmmdo..',
    '...ommmmmmmddo..',
    '....ommmmmddo...',
    '.....oommddo....',
    '.......oooo.....',
    '................',
    '................',
    '................',
  ],
  wood: [
    '................',
    '................',
    '...........oo...',
    '..........omdo..',
    '.........ommdo..',
    '........ommdo...',
    '.......ommdo....',
    '..oo..ommdo.....',
    '.omlooommdo.....',
    '..ooommmdo......',
    '....ommdo.......',
    '...ommdo........',
    '..ommdo.........',
    '..oddo..........',
    '...oo...........',
    '................',
  ],
  flower: [
    '................',
    '......oooo......',
    '.....ommmmo.....',
    '..oooomlmmoooo..',
    '.ommmmoyyommmmo.',
    '.ommlmoyyommmmo.',
    '..ooooommoooooo.',
    '.....ommmmo.....',
    '......oooo......',
    '.......go.......',
    '....oo.go.......',
    '...oggogo.......',
    '....oogo........',
    '.......go.......',
    '.......go.......',
    '................',
  ],
  bell: [
    '................',
    '......oo........',
    '.....ogo........',
    '....ogo.........',
    '...ogo..........',
    '...go...oo......',
    '..oooo.ommo.....',
    '.ommmmoommmo....',
    '.omlmmoomlmmo...',
    '.ommmmoommmmo...',
    '.ommmmo.ommmo...',
    '.odmdmo.odmdo...',
    '..o.o....o.o....',
    '................',
    '................',
    '................',
  ],
  cone: [
    '................',
    '.......oo.......',
    '......omlo......',
    '.....odmmdo.....',
    '....ommlmmmo....',
    '....odmmdmdo....',
    '...ommlmmlmmo...',
    '...odmmdmmdmo...',
    '...ommlmmlmmo...',
    '....odmmdmdo....',
    '....ommlmmmo....',
    '.....odmmdo.....',
    '......oddo......',
    '.......oo.......',
    '................',
    '................',
  ],
  jar: [
    '................',
    '.....oooooo.....',
    '....okkkkkko....',
    '.....oooooo.....',
    '....owwwwwwo....',
    '...owwwwwwwwo...',
    '...owwyywwwwo...',
    '...owyYYywwwo...',
    '...owwyywwyyo...',
    '...owwwwwyYyo...',
    '...owwwwwwyyo...',
    '...owwwwwwwwo...',
    '....owwwwwwo....',
    '.....oooooo.....',
    '................',
    '................',
  ],
  turnip: [
    '................',
    '.....oo..oo.....',
    '....oggooggo....',
    '.....oggggo.....',
    '......oggo......',
    '.....opppo......',
    '....oppwwwo.....',
    '...opwwwwwwo....',
    '...owwwwwwwo....',
    '...owwwwwwdo....',
    '....owwwwddo....',
    '.....oddddo.....',
    '......oddo......',
    '.......oo.......',
    '................',
    '................',
  ],
  carrot: [
    '................',
    '.........o.o.o..',
    '........ogogog..',
    '.........ogggo..',
    '........ommmoo..',
    '.......omlmmo...',
    '......omlmmdo...',
    '......ommmdo....',
    '.....ommmdo.....',
    '.....ommddo.....',
    '....ommdo.......',
    '....omddo.......',
    '...omdo.........',
    '...odo..........',
    '...oo...........',
    '................',
  ],
  strawberry: [
    '................',
    '......o.o.......',
    '.....ogogo......',
    '....ogggggo.....',
    '....ommmmmo.....',
    '...ommwmmmmo....',
    '...omlmmwmmo....',
    '...ommmmmmdo....',
    '...omwmmwmdo....',
    '....ommmmmo.....',
    '....ommmmdo.....',
    '.....omddo......',
    '......oo........',
    '................',
    '................',
    '................',
  ],
  sunflower: [
    '................',
    '.....o.oo.o.....',
    '....oyoyyoyo....',
    '...oyyyyyyyyo...',
    '..oyyykkkkyyyo..',
    '...oyykdkkkyo...',
    '..oyyykkkdyyyo..',
    '...oyykkkkyyo...',
    '....oyyyyyyo....',
    '.....oyoyyo.....',
    '.......go.......',
    '....oo.go.oo....',
    '...ogggoggggo...',
    '....oo.go.oo....',
    '.......go.......',
    '................',
  ],
  pumpkin: [
    '................',
    '.......oo.......',
    '.......ogo......',
    '....oooogooo....',
    '...ommdmmmdmo...',
    '..omlmdmmmdmmo..',
    '..ommmdmlmdmmo..',
    '.ommmmdmmmdmmmo.',
    '.ommmmdmmmdmmmo.',
    '.odmmmdmmmdmmdo.',
    '..odmmdmmmdmdo..',
    '...oddddddddo...',
    '....oooooooo....',
    '................',
    '................',
    '................',
  ],
  moonbloom: [
    '................',
    '......oooo......',
    '....oowwwwoo....',
    '...owwlwwlwwo...',
    '..owlwwmmwwlwo..',
    '..owwwmyymwwwo..',
    '..owlwmyymwlwo..',
    '..owwwwmmwwwwo..',
    '...owlwwwwlwo...',
    '....oowwwwoo....',
    '......ogo.......',
    '......ogo.......',
    '....oogggoo.....',
    '.......go.......',
    '................',
    '................',
  ],
  seeds: [
    '................',
    '...oooooooooo...',
    '..owwwwwwwwwwo..',
    '..owkkkkkkkkwo..',
    '..owkmmmmmmkwo..',
    '..owkmmmmmmkwo..',
    '..owkmmmmmmkwo..',
    '..owkkkkkkkkwo..',
    '..owwwwwwwwwwo..',
    '..owwgggwwwwwo..',
    '..owwwwwwwwwwo..',
    '..odddddddddddo.',
    '...oooooooooooo.',
    '................',
    '................',
    '................',
  ],
  bread: [
    '................',
    '................',
    '................',
    '......oooooo....',
    '....oommlmmmoo..',
    '...ommlmmmlmmmo.',
    '..omlmdmmdmmdmo.',
    '..ommdmmdmmdmmo.',
    '..ommmmmmmmmmdo.',
    '..odmmmmmmmmddo.',
    '...odddddddddo..',
    '....ooooooooo...',
    '................',
    '................',
    '................',
    '................',
  ],
  tart: [
    '................',
    '................',
    '................',
    '....oooooooo....',
    '..ooyrrryrrryoo.',
    '.oyrrwrrrrwrrryo',
    '.oyrrrrrrrrrrryo',
    '.oyyrrrwrrrrryyo',
    '.odyyyyyyyyyyydo',
    '.odmmmmmmmmmmmdo',
    '..odddddddddddo.',
    '...ooooooooooo..',
    '................',
    '................',
    '................',
    '................',
  ],
  cookie: [
    '................',
    '................',
    '.....oooooo.....',
    '....ommmmmmo....',
    '...omlmkmmmmo...',
    '..ommmmmmmkmmo..',
    '..omkmmmlmmmmo..',
    '..ommmmmmmmkmo..',
    '..ommmkmmmmmdo..',
    '...ommmmmkmdo...',
    '....oddmmddo....',
    '.....oooooo.....',
    '................',
    '................',
    '................',
    '................',
  ],
  cup: [
    '................',
    '.......o..o.....',
    '......o..o......',
    '.......o..o.....',
    '...oooooooooo...',
    '...okkkkkkkkoo..',
    '...owwwwwwwwo.o.',
    '...owlwwwwwwo.o.',
    '...owwwwwwwwoo..',
    '...owwwwwwwdo...',
    '....owwwwwdo....',
    '..oooddddddooo..',
    '..odddddddddddo.',
    '...ooooooooooo..',
    '................',
    '................',
  ],
  can: [
    '................',
    '................',
    '......oooo......',
    '.....oo..oo.....',
    '...oommmmmmoo...',
    '..omlmmmmmmmmo.o',
    '..omlmmmmmmmmoomo',
    '..ommmmmmmmmmmmo.',
    '..ommmmmmmmmmmo..',
    '..ommmmmmmmmdo...',
    '..odmmmmmmmmdo...',
    '..oddddddddddo...',
    '...oooooooooo....',
    '................',
    '................',
    '................',
  ],
  rod: [
    '...............o',
    '..............ol',
    '.............olo',
    '............omo.',
    '...........omo.w',
    '..........omo..w',
    '.........omo...w',
    '........omo....w',
    '.......omo.....w',
    '......omo......w',
    '....oommo.....oro',
    '...okkkko.....oo',
    '..okkkko........',
    '..okkoo.........',
    '...oo...........',
    '................',
  ],
  net: [
    '................',
    '......oooo......',
    '....oowwwwoo....',
    '...owwowwowwo...',
    '...owowwowowo...',
    '...owwowwowwo...',
    '....owowwowo....',
    '.....oowwoo.....',
    '.......oo.......',
    '.......oko......',
    '.......oko......',
    '.......oko......',
    '.......oko......',
    '.......oko......',
    '........o.......',
    '................',
  ],
  shard: [
    '................',
    '.......oo.......',
    '......owlo......',
    '.....owllmo.....',
    '.....owlmmo.....',
    '....owllmmmo....',
    '....owlmmmmo....',
    '...owllmmmmdo...',
    '...owlmmmmmdo...',
    '...owlmmmmddo...',
    '....olmmmmdo....',
    '....ommmmddo....',
    '.....ommddo.....',
    '......oddo......',
    '.......oo.......',
    '................',
  ],
  key: [
    '................',
    '................',
    '....oooo........',
    '...ommmmo.......',
    '..omlooomo......',
    '..omo..omo......',
    '..omo..omo......',
    '...ommmmdo......',
    '....oommo.......',
    '......omo.......',
    '......omoo......',
    '......ommo......',
    '......omo.......',
    '......omoo......',
    '......oooo......',
    '................',
  ],
  page: [
    '................',
    '...oooooooo.....',
    '...owwwwwwoo....',
    '...owkkkwwowo...',
    '...owwwwwwoooo..',
    '...owkkkkkkkwo..',
    '...owwwwwwwwwo..',
    '...owkkkkkkwwo..',
    '...owwwwwwwwwo..',
    '...owkkkkkkkwo..',
    '...owwwwwwwwwo..',
    '...owkkkkwwwwo..',
    '...owwwwwwwwwo..',
    '...ooooooooooo..',
    '................',
    '................',
  ],
  book: [
    '................',
    '................',
    '...ooooooooooo..',
    '..ommmmmmmmmmwo.',
    '..omlmmmmmmmmwo.',
    '..ommmyyyymmmwo.',
    '..ommmymmymmmwo.',
    '..ommmyyyymmmwo.',
    '..ommmmmmmmmmwo.',
    '..ommmmmmmmmmwo.',
    '..odddddddddddwo',
    '...ooooooooooooo',
    '................',
    '................',
    '................',
    '................',
  ],
  kite: [
    '................',
    '.......oo.......',
    '......ommo......',
    '.....omlmmo.....',
    '....omlmmmmo....',
    '...ommmwmmmmo...',
    '....ommwmmmo....',
    '.....ommmmo.....',
    '......omdo......',
    '.......oo.......',
    '........o.......',
    '.......k.o......',
    '........o.......',
    '.......k.o......',
    '........o.......',
    '................',
  ],
  lantern: [
    '................',
    '.......oo.......',
    '......o..o......',
    '.....oooooo.....',
    '....ommmmmmo....',
    '...omlyyyymmo...',
    '...omyYYYyymo...',
    '...omyYYYyymo...',
    '...omyyyyyymo...',
    '...ommmmmmmmo...',
    '....ommmmmmo....',
    '.....oooooo.....',
    '......o..o......',
    '................',
    '................',
    '................',
  ],
  chair: [
    '................',
    '....oooooooo....',
    '....ommmmmmo....',
    '....omlmmmmo....',
    '....ommmmmmo....',
    '....ommmmmmo....',
    '...oooooooooo...',
    '...ommmmmmmmo...',
    '...odddddddddo..',
    '...oo......oo...',
    '...om......mo...',
    '...om......mo...',
    '...om......mo...',
    '...oo......oo...',
    '................',
    '................',
  ],
  box: [
    '................',
    '................',
    '..oooooooooooo..',
    '..omlmmmmmmmmo..',
    '..ommmmmmmmmmo..',
    '..ommmmmmmmmmo..',
    '..odddddddddddo.',
    '..ommmmmmmmmmo..',
    '..ommmmwwmmmmo..',
    '..ommmmmmmmmmo..',
    '..ommmmmmmmmmo..',
    '..odddddddddddo.',
    '..oooooooooooo..',
    '................',
    '................',
    '................',
  ],
  hat: [
    '................',
    '................',
    '................',
    '.....oooooo.....',
    '....omlmmmmo....',
    '...omlmmmmmmo...',
    '...ommmmmmmmo...',
    '...okkkkkkkko...',
    '.ooommmmmmmmooo.',
    'ommmmmmmmmmmmmmo',
    'oddddddddddddddo',
    '.oooooooooooooo.',
    '................',
    '................',
    '................',
    '................',
  ],
  shirt: [
    '................',
    '................',
    '...ooo....ooo...',
    '..ommmoooommmo..',
    '.ommmmwwwwmmmmo.',
    'ommmmmmwwmmmmmmo',
    'ommmlmmmmmmmmmmo',
    '.ooommmmmmmmooo.',
    '...ommmmmmmmo...',
    '...ommmmmmmmo...',
    '...ommmmmmmmo...',
    '...odddddddddo..',
    '....oooooooooo..',
    '................',
    '................',
    '................',
  ],
  glasses: [
    '................',
    '................',
    '................',
    '................',
    '................',
    '.oooooo..oooooo.',
    'ommwmmmooommwmmo',
    'ommmmmmo.ommmmmo',
    'odmmmmdo.odmmmdo',
    '.oooooo...ooooo.',
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
  ],
  swatch: [
    '................',
    '................',
    '..oooooooooooo..',
    '..ommmmmmmmmmo..',
    '..omlmlmlmlmlo..',
    '..ommmmmmmmmmo..',
    '..omlmlmlmlmlo..',
    '..ommmmmmmmmmo..',
    '..omlmlmlmlmlo..',
    '..ommmmmmmmmmo..',
    '..omlmlmlmlmlo..',
    '..odddddddddddo.',
    '..oooooooooooo..',
    '................',
    '................',
    '................',
  ],
  star: [
    '................',
    '.......oo.......',
    '......omlo......',
    '......omlo......',
    '.oooooommooooo..',
    '.omllmmmmmmmmo..',
    '..ommmmmmmmmo...',
    '...ommmmmmmo....',
    '...ommmmmmmo....',
    '..ommmmoommmo...',
    '..ommoo..oommo..',
    '..ooo......ooo..',
    '................',
    '................',
    '................',
    '................',
  ],
  feather: [
    '................',
    '............oo..',
    '...........olmo.',
    '..........olmmo.',
    '.........olmmmo.',
    '........olmmmo..',
    '.......olmmmdo..',
    '......olmmmdo...',
    '.....olmmmdo....',
    '....olmmmdo.....',
    '...olmmddo......',
    '...ommddo.......',
    '..okoddo........',
    '.ok.oo..........',
    'ok..............',
    '................',
  ],
  wheat: [
    '................',
    '......o..o......',
    '.....olo.olo....',
    '.....omo.omo....',
    '....olmo.omlo...',
    '....omdo.odmo...',
    '.....omo.omo....',
    '....olmo.omlo...',
    '....omdo.odmo...',
    '.....omo.omo....',
    '......oggo......',
    '......oggo......',
    '.....oyyyyo.....',
    '......oggo......',
    '......oggo......',
    '.......oo.......',
  ],
  egg: [
    '................',
    '................',
    '................',
    '......oooo......',
    '.....ohllmo.....',
    '....ohlmmmmo....',
    '....olmmmmmo....',
    '...olmmmmmmmo...',
    '...ommmmmmmmo...',
    '...ommmmmmmdo...',
    '...ommmmmmmdo...',
    '....ommmmmdo....',
    '....oddmmddo....',
    '.....oooooo.....',
    '................',
    '................',
  ],
  bottle: [
    '................',
    '......okko......',
    '......okko......',
    '......olmo......',
    '.....olmmmo.....',
    '....olmmmmmo....',
    '....olmwwmmo....',
    '....olmwwmmo....',
    '....olmwwmmo....',
    '....olmwwmmo....',
    '....olmmmmmo....',
    '....olmmmmdo....',
    '....ommmmmdo....',
    '....oddddddo....',
    '.....oooooo.....',
    '................',
  ],
  bike: [
    '................',
    '................',
    '..........ooo...',
    '.........okko...',
    '....oo....o.....',
    '...ommo..omo....',
    '....oommmmmo....',
    '..ooo.o...o.ooo.',
    '.o...oo..o.o...o',
    'o...o.o.o...o..o',
    'o..o..ooo....o.o',
    'o.....o.o......o',
    '.o...o...o....o.',
    '..ooo.....oooo..',
    '................',
    '................',
  ],
  coin: [
    '................',
    '................',
    '.....oooooo.....',
    '....ommmmmmo....',
    '...omlmmmmmmo...',
    '..omlmmoommmmo..',
    '..ommmommommmo..',
    '..ommmommommmo..',
    '..ommmommommmo..',
    '..ommmmoommmdo..',
    '...ommmmmmmdo...',
    '....oddddddo....',
    '.....oooooo.....',
    '................',
    '................',
    '................',
  ],
};

function palette(base, extra = {}) {
  const R = ramp(base);
  return { o: R.o, d: R.d, m: R.m, l: R.l, h: R.h, w: '#fff8ec', k: '#3b2a2e', g: '#5fa453', y: '#ffd66b', Y: '#fff3a6', r: '#d9364a', p: '#9a6ad0', ...extra };
}

const RECIPES = {
  fish_minnow: ['fish', '#9fb4c4', { l: '#dfe9ef', k: '#2a2433' }],
  fish_trout: ['fish', '#8aa86a', { l: '#e8d9b0', k: '#2a2433' }],
  fish_carp: ['fish', '#c49a50', { l: '#f0dca0', k: '#2a2433' }],
  fish_koi: ['fish', '#f0934a', { l: '#fff8ec', k: '#2a2433' }],
  fish_goldfish: ['fish', '#f2a23a', { l: '#ffd66b', k: '#2a2433' }],
  fish_sardine: ['fish', '#7a9ab8', { l: '#e3edf5', k: '#2a2433' }],
  fish_mackerel: ['fish', '#4e8ab0', { l: '#cfe3ee', k: '#2a2433' }],
  fish_moonfin: ['fish', '#c8d8f0', { l: '#ffffff', k: '#3a4a86', m: '#dfe8ff' }],
  fish_crab: ['crab', '#e0603f', { k: '#2a2433' }],
  fish_puffer: ['puffer', '#e8c45a', { l: '#fff3c0', k: '#2a2433' }],
  fish_boot: ['boot', '#8a5d42', {}],
  fish_seaweed: ['seaweed', '#4f955a', {}],
  berry: ['berry', '#b8364a', { g: '#4f955a' }],
  apple: ['apple', '#e0463f', { k: '#6b4330', g: '#5fa453' }],
  mushroom: ['mushroom', '#d9594c', { l: '#f4ead8', d: '#a8453a' }],
  shell: ['shell', '#f7c9b8', {}],
  seaglass: ['glass', '#8fd6c8', {}],
  branch: ['wood', '#a8744a', {}],
  daisy: ['flower', '#f4f1ec', { y: '#ffd66b' }],
  poppy: ['flower', '#e0403f', { y: '#3b2a2e' }],
  bluebell: ['bell', '#6a8ae0', {}],
  pinecone: ['cone', '#8e5d3e', {}],
  firefly: ['jar', '#dcecf7', {}],
  turnip: ['turnip', '#f4f1ec', { p: '#b86ab0', w: '#f4f1ec', d: '#d8d0e0' }],
  carrot: ['carrot', '#e8883a', {}],
  strawberry: ['strawberry', '#e0403f', { w: '#ffe4a0' }],
  sunflower: ['sunflower', '#ffd66b', { y: '#ffd66b', k: '#6b4330', d: '#3b2a2e' }],
  pumpkin: ['pumpkin', '#e8883a', { g: '#5fa453' }],
  moonbloom: ['moonbloom', '#b9d8ff', { w: '#e6f0ff', m: '#9fb8ff', l: '#ffffff' }],
  bread: ['bread', '#d9a05a', {}],
  tart: ['tart', '#c8704a', { r: '#c8364a', w: '#ffe0e8', y: '#e8b86a' }],
  cookie: ['cookie', '#d9a86a', { k: '#6b4330' }],
  coffee: ['cup', '#f4efe4', { k: '#8a5d42', w: '#f4efe4', d: '#c8704a' }],
  cocoa: ['cup', '#f4a4b6', { k: '#6b4330', w: '#f4a4b6', d: '#c86a8a' }],
  can: ['can', '#4f8ab8', {}],
  rod: ['rod', '#c49a64', { k: '#6b4330', r: '#d9364a', w: '#e9e4f0' }],
  net: ['net', '#c49a64', { w: '#eae4d8', k: '#8e5d3e' }],
  hoe: ['rod', '#9a95a0', { k: '#6b4330' }],
  shard: ['shard', '#8fe0ff', { w: '#ffffff', l: '#c9f2ff' }],
  key_home: ['key', '#e0a526', {}],
  page: ['page', '#fbf1dc', { w: '#fbf1dc', k: '#9a8a80' }],
  recipe: ['book', '#c8454f', { y: '#ffd66b', w: '#fbf1dc' }],
  kite: ['kite', '#d9364a', { k: '#6b4330', w: '#fff8ec' }],
  pick: ['shell', '#8fd6b4', {}],
  lantern: ['lantern', '#e97d8f', {}],
  u_rod: ['rod', '#e0a526', { k: '#6b4330', r: '#d9364a', w: '#e9e4f0' }],
  u_can: ['can', '#e0a526', {}],
  fish_perch: ['fish', '#a8b050', { l: '#f0e8b0', k: '#2a2433' }],
  fish_char: ['fish', '#d9705a', { l: '#f4d8c8', k: '#2a2433' }],
  fish_icefin: ['fish', '#a9cdec', { l: '#ffffff', k: '#3a4a86', m: '#cfe6f7' }],
  fish_catfish: ['fish', '#6a6a4a', { l: '#c8c0a0', k: '#2a2433' }],
  fish_bass: ['fish', '#5f8a4f', { l: '#d8e8b0', k: '#2a2433' }],
  fish_pike: ['fish', '#6a7a58', { l: '#e0d8a0', k: '#2a2433', w: '#fff8ec' }],
  fish_eel: ['fish', '#3a4a86', { l: '#9fb8ff', k: '#fff3c4', m: '#4f5fa0' }],
  feather: ['feather', '#e3e7ee', {}],
  starfish: ['star', '#f0934a', {}],
  glowcap: ['mushroom', '#4fd8e0', { l: '#e9f0e0', d: '#2fa8b0' }],
  lavender: ['bell', '#9b7ad8', {}],
  wheat: ['wheat', '#e8c46a', { g: '#8aa64a', y: '#c9a44e' }],
  egg: ['egg', '#f1e2c8', {}],
  pearl: ['egg', '#efe9f6', {}],
  relic: ['coin', '#c8904a', {}],
  milk: ['bottle', '#f4f1ec', { w: '#7cb6e0', k: '#7cb6e0' }],
  honey: ['jar', '#e0a526', { w: '#f2b63d', y: '#ffd66b', Y: '#fff3a6', k: '#c8454f' }],
  smore: ['cookie', '#c8905a', { k: '#6b4330' }],
  bottle: ['bottle', '#8fd6b4', { w: '#fbf1dc', k: '#8e5d3e' }],
  map: ['page', '#e9d4a8', { w: '#e9d4a8', k: '#c8454f' }],
  sailcloth: ['page', '#f4f1ec', { w: '#f4f1ec', k: '#c9b797' }],
  lamp_hand: ['lantern', '#f6c65b', {}],
  bike: ['bike', '#d9364a', { o: '#3b2a2e', k: '#8e5d3e' }],
  seed_wheat: ['seeds', '#e8c46a', { w: '#fbf1dc', k: '#c9a77c' }],
  coin: ['coin', '#f6c65b', {}],
};

const cache = new Map();

export function itemIcon(id) {
  let c = cache.get(id);
  if (c) return c;
  const def = ITEMS[id] || {};
  let shape = 'box', base = '#b07b50', extra = {};
  if (RECIPES[id]) [shape, base, extra] = RECIPES[id];
  else if (def.cat === 'seed') { shape = 'seeds'; const crop = RECIPES[def.crop]; base = crop ? crop[1] : '#7fbf5a'; extra = { w: '#fbf1dc', k: '#c9a77c' }; }
  else if (def.cat === 'furniture') { shape = def.furn === 'chair' || def.furn === 'sofa' ? 'chair' : 'box'; base = { plant: '#5fa453', lamp: '#f6d38f', rug: '#d9a05a', tank: '#7cc4e8', teddy: '#b07b50', petbed: '#e97d8f', painting: '#3a7cae', candles: '#fbf1dc', vase: '#7cb6e0', strings: '#ffd66b', globe: '#4e73b6', piano: '#3b2a2e', sofa: '#8a64b8', radio: '#c8704a', shipbottle: '#8fd6c8', haybale: '#e0bf62', telescope: '#e0a526', minilight: '#d65a4f', musicbox: '#b07b50', lanternset: '#ec5f73', terrarium: '#6f9a55' }[def.furn] || '#a8744a'; }
  else if (def.cat === 'decor') { shape = 'swatch'; base = def.wall ? { rose: '#f4c6cf', mint: '#cfe8d6', night: '#3a4a86', honey: '#d9a86a' }[def.wall] : { check: '#e9b7bf', dark: '#6b4330', moss: '#6f9a55' }[def.floor]; }
  else if (def.cat === 'clothes') {
    const [slot, v] = def.unlock;
    if (slot === 'hat') { shape = 'hat'; base = { frog: '#7fbf5a', witch: '#6a4a9a', crown: '#f2c14e', catears: '#3b3844', straw: '#e8c46a', tophat: '#3b3844' }[v] || '#c8454f'; }
    else if (slot === 'top') { shape = 'shirt'; base = { haori: '#3f9b98', smock: '#efe3c8' }[v] || '#7cb6e0'; }
    else { shape = v === 'shades' ? 'glasses' : 'shirt'; base = v === 'shades' ? '#3b3844' : '#d06b8e'; }
  }
  const pal = palette(base, extra);
  const rows = S[shape] || S.box;
  c = makeCanvas(16, 16);
  for (let y = 0; y < 16; y++) {
    const row = rows[y] || '';
    for (let x = 0; x < 16; x++) {
      const ch = row[x];
      if (!ch || ch === '.') continue;
      const color = pal[ch];
      if (!color) continue;
      c.ctx.fillStyle = color;
      c.ctx.fillRect(x, y, 1, 1);
    }
  }
  cache.set(id, c);
  return c;
}

export function drawIcon(ctx, id, x, y, scale = 1) {
  const c = itemIcon(id);
  ctx.drawImage(c, 0, 0, 16, 16, Math.round(x), Math.round(y), 16 * scale, 16 * scale);
}
