// Villager dialogue content. {name} = player, {pet} = pet name.
// Pools are picked from by friendship tier, time of day and weather.

export const LINES = {
  hollis: {
    intro: [
      ['happy', 'Well, well! You must be June’s grandchild. I’d know that look anywhere — she used to stand on this very pier, squinting at the sea just like that.'],
      ['neutral', 'I’m Hollis, mayor of Marigold Cove. Population: small, but very enthusiastic about soup.'],
    ],
    pool: [
      'Did you know the town hall clock has been exactly four minutes fast since 1982? We consider it a local treasure.',
      'Your Nana June kept the lighthouse burning for forty years. Folks set their clocks by that light.',
      'I’ve got a speech prepared for every occasion. Birthdays, weddings, particularly large turnips…',
      'The cove’s been quiet since the light went out. People stay inside more. I miss the noise, honestly.',
      'Rosa’s bread and Sol’s coffee — that’s how every good day in Marigold Cove begins.',
      'If you ever need anything, my door’s open. Well — the door sticks. But it’s open in spirit!',
    ],
    warm: [
      'You know, you’ve brought a little spark back to this place. I can feel it in my old bones.',
      'June wrote to me about you, years ago. "Kind to a fault," she said. She was right, as usual.',
      'Between us — I’m terrible at fishing. Don’t tell Finn. He thinks I let him win.',
    ],
    morning: ['Morning, {name}! The gulls are singing and the kettle’s on. Splendid day for it, whatever "it" is.'],
    evening: ['Ah, golden hour. June always said the cove looks like a painting right about now.'],
    night: ['Out late, {name}? Mind the lamps are lit on the way home. Old Glimmer used to do that for all of us…'],
    rain: ['A bit of rain never hurt anyone. It’s wonderful for the gardens — and for staying in with cocoa.'],
    gift: {
      love: 'Oh my! This is marvellous. You’ve made an old mayor very happy indeed.',
      like: 'How thoughtful of you! Thank you kindly.',
      neutral: 'Why, thank you, {name}. Every little kindness counts.',
      hate: 'Ah… well. It’s the thought that counts! Mostly.',
    },
  },
  rosa: {
    intro: [
      ['surprised', 'Oh! A new face! Come in, come in — mind the flour, it gets everywhere. Including my eyebrows.'],
      ['happy', 'I’m Rosa. I bake, I worry, and I make sure nobody in this cove goes hungry. You’re June’s grandkid? Then you’re family.'],
    ],
    pool: [
      'The secret to good bread is patience. And butter. Mostly butter.',
      'Pip’s off adventuring again. Last week he "discovered" the fountain. He’s very proud.',
      'I wake up at four every morning to start the ovens. The cove smells like cinnamon before the sun is even up!',
      'If you find wild berries, bring them my way. I have plans. Delicious, sticky plans.',
      'Everyone says my Sunrise Loaf tastes like a warm hug. I think it’s the honey.',
      'Have you tried the café yet? Sol and I have a deal — he never bakes, and I never make coffee.',
    ],
    warm: [
      'You’re a sweetheart, you know that? I saved you the end piece of the loaf. The crunchy one.',
      'Pip talks about you all the time now. "Did you know {name} caught a fish THIS big?"',
      'Being a single mum and a baker is a lot. Having good friends around makes it lighter.',
    ],
    morning: ['Fresh out of the oven! Well, the bread is. I’ve been out of the oven for years.'],
    evening: ['The ovens are cooling and my feet are aching. Best part of the day!'],
    night: ['Shouldn’t you be tucked in? Growing folks need their sleep. So do tired bakers.'],
    rain: ['Rainy days are baking days. Not that every day isn’t a baking day.'],
    gift: {
      love: 'Oh, for me?! This is exactly what I needed. Come here, you — hug!',
      like: 'How lovely! Thank you, dear.',
      neutral: 'Thank you, sweetheart. That’s very kind.',
      hate: 'Oh! Um. I’ll… find a use for it. Somewhere. Far from the kitchen.',
    },
  },
  pip: {
    intro: [
      ['surprised', 'WHOA. Are you a pirate? You came on a BOAT.'],
      ['happy', 'I’m Pip! I’m an adventurer. I’ve explored the whole cove. Twice. Except the scary parts.'],
    ],
    pool: [
      'Did you know crabs walk sideways? I tried it. It’s hard.',
      'I found a rock that looks like a potato. Want to see? …I lost it.',
      'Mom says I can’t go in the woods after dark. Are there bears? There’s probably bears.',
      'When I grow up I’m gonna be a lighthouse keeper. Or a dragon. Still deciding.',
      'I can burp the alphabet up to G!',
      'The fountain wishes don’t work. I wished for a pony. Nothing. Rude.',
    ],
    warm: [
      'You’re my best friend. Don’t tell my other best friend. (It’s the fountain.)',
      'I saved you a cool shell! …Okay I lost it. But I SAVED it for a while.',
      'Can we go on an adventure together? A real one? With snacks?',
    ],
    morning: ['I’ve been awake since FOREVER. The sun and me are best buds.'],
    evening: ['Mom says dinner soon. I’m gonna explore until she yells my name three times.'],
    night: ['*yawn* I’m not sleepy. I’m just… resting my eyes… standing up…'],
    rain: ['Puddles are just baby lakes! I’m gonna jump in ALL of them!'],
    gift: {
      love: 'WHOAAA! This is the BEST thing anyone ever gave me EVER!',
      like: 'Cool! Thanks!',
      neutral: 'Uh… thanks! I guess!',
      hate: 'Bleh! Grown-up stuff. Here, you keep it. No, I insist.',
    },
  },
  finn: {
    intro: [
      ['neutral', 'Oh. Hey. You’re the one who took the ferry in? It only comes in once a week, so… you’re kind of big news.'],
      ['happy', 'I’m Finn. I fish. That’s… mostly it. The sea’s good company. Doesn’t ask a lot of questions.'],
    ],
    pool: [
      'Sardines run thick near the pier in the mornings. Mackerel if you’re patient.',
      'My grandpa used to say the sea remembers everyone who loves it. I hope he’s right.',
      'Fishing’s mostly waiting. I’m good at waiting. Less good at talking. You’re easy to talk to, though.',
      'You can fish in the river and the pond too. Different water, different fish.',
      'Ever see the water at night? It sparkles. Something to do with tiny glowing critters.',
      'Rain’s good for fishing. The fish don’t mind getting wet.',
    ],
    warm: [
      'I don’t usually… have people to fish with. This is nice.',
      'Grandpa would’ve liked you. He liked anyone who didn’t scare the fish.',
      'You’re getting good with that rod. Better than me at your age. Don’t let it go to your head.',
    ],
    morning: ['Best bites are at dawn. The sea’s still sleepy.'],
    evening: ['Evening tide’s coming in. Listen — you can hear it breathing.'],
    night: ['Night fishing’s the best. Just you, the stars, and whatever’s down there.'],
    rain: ['Rain’s nothing. Try a winter storm on a dinghy.'],
    gift: {
      love: 'Whoa… you got this for me? That’s… really cool. Thanks. Seriously.',
      like: 'Nice. Thanks.',
      neutral: 'Oh. Thanks, I guess.',
      hate: 'Uh. Flowers make me sneeze. But thanks for thinking of me.',
    },
  },
  ivy: {
    intro: [
      ['happy', 'Hi there! Welcome to Petal & Seed — oh! You’re June’s grandchild! Her garden was the prettiest in the cove.'],
      ['neutral', 'I’m Ivy. I grow things. Flowers, veggies, the occasional existential crisis about aphids.'],
    ],
    pool: [
      'Plants just need three things: sunlight, water, and someone who talks to them. I’m very chatty.',
      'Turnips grow in three days. Pumpkins take five, but they’re worth their weight in coins.',
      'Did you know sunflowers follow the sun? Wish I had that much commitment.',
      'Water your crops every day and they’ll grow. Rain counts too — nature’s watering can!',
      'The meadow across the river has flowers you can’t find anywhere else. Bluebells, poppies…',
      'Your Nana’s soil is still good, you know. Rich and dark. She took such good care of it.',
    ],
    warm: [
      'You have a green thumb. I can tell. Your plants look so happy!',
      'I named a rose after you. Don’t worry, it’s a very pretty rose.',
      'Sometimes I sit in the garden and just… breathe. You should try it. Want company?',
    ],
    morning: ['Good morning! The dew’s still on the petals. It’s the best time to be a plant person.'],
    evening: ['Golden hour makes everything look like it’s glowing. Plants love it too.'],
    night: ['The moonflowers open at night. Everything has its own time to bloom.'],
    rain: ['Rain! The garden is doing a happy little dance right now, I just know it.'],
    gift: {
      love: 'Oh!! It’s beautiful! You really understand me, don’t you?',
      like: 'Aww, thank you! This is lovely.',
      neutral: 'Thank you! That’s sweet.',
      hate: 'Oh… oh no. This is not a plant. This is the opposite of a plant.',
    },
  },
  theo: {
    intro: [
      ['neutral', 'Huh. New neighbor. Theo. Carpenter.'],
      ['happy', 'Need a chair, a table, a birdhouse, a bigger house? I build it. Just don’t ask me to build a speech. That’s the mayor’s thing.'],
    ],
    pool: [
      'Measure twice, cut once. Measure three times if it’s for Rosa. She notices.',
      'The east bridge washed out in the big storm. Been meaning to fix it. Need wood, and coin.',
      'Good wood’s everywhere if you look. Fallen branches in the woods. Bring ’em by.',
      'I made half the furniture in this cove. The wobbly half was my apprentice years.',
      'Coffee. Sawdust. Silence. That’s the good life.',
      'Your Nana’s cottage? I fixed that roof three times. She always paid in pie.',
    ],
    warm: [
      'You work hard. I respect that.',
      'Carved something for you. It’s a duck. Or a boat. Depends how you hold it.',
      'Don’t tell anyone, but I like when you visit. The shop gets quiet.',
    ],
    morning: ['Early start. Wood doesn’t cut itself.'],
    evening: ['Day’s work done. Good tired.'],
    night: ['Late. Go home. Sleep’s the best tool you’ve got.'],
    rain: ['Rain means I work inside. The shop smells like cedar when it rains.'],
    gift: {
      love: 'Huh. That’s… really good. Thanks. You didn’t have to.',
      like: 'Nice. I’ll use this.',
      neutral: 'Thanks.',
      hate: 'I’m… not a flower guy.',
    },
  },
  mabel: {
    intro: [
      ['neutral', 'Shh — oh. No need, it’s only us. Welcome to the Seashell Library. I’m Mabel.'],
      ['happy', 'June’s grandchild… my, my. She borrowed "The Sea’s Many Moods" in 1994. She still has it, I’m sure. I’ve decided not to charge the late fee.'],
    ],
    pool: [
      'Every book is a door. Some doors are just very, very slow.',
      'I’ve read every book in this library twice. The cookbook three times, for reasons I won’t discuss.',
      'Old Glimmer has a legend, you know. It’s written in a book I… misplaced some pages of. The wind took them.',
      'A cup of cocoa and a good mystery. Nothing better on a cold evening.',
      'When I was young, I wanted to see the whole world. Then I realized the whole world is in these shelves.',
      'Do keep your voice at a pleasant murmur. The books are sleeping.',
    ],
    warm: [
      'You remind me of June. She always asked the right questions.',
      'I’ve set aside a book for you. It’s about lighthouses. I thought you’d like it.',
      'Friendship is like a good book, dear. The best part is somewhere in the middle, when you can’t put it down.',
    ],
    morning: ['Morning light is best for reading. It’s soft on the eyes and kind to the pages.'],
    evening: ['The library is loveliest at dusk. The dust sparkles.'],
    night: ['I read by candlelight at night. Terrible for the eyes. Wonderful for the soul.'],
    rain: ['Rain on the library roof is my favorite sound in the world.'],
    gift: {
      love: 'Oh my… how wonderfully thoughtful. You’ve quite made my week.',
      like: 'How kind. Thank you, dear.',
      neutral: 'Thank you. I’ll find a place for it.',
      hate: 'Oh dear. Perhaps… not near the books.',
    },
  },
  sol: {
    intro: [
      ['happy', 'Hey hey! Welcome to the Driftwood! You look like you could use a latte. Everyone could use a latte.'],
      ['neutral', 'I’m Sol. I make the coffee, I play the tunes, I tell the jokes. Only one of those is optional.'],
    ],
    pool: [
      'Every evening I play by the fountain. Come listen! Requests welcome, but I only know nine songs.',
      'Coffee’s just bean soup if you think about it. Please don’t think about it.',
      'I came here to "visit for a week". That was six years ago.',
      'The best songs come from quiet places. Marigold Cove is full of quiet places.',
      'Finn sits in the corner every evening and orders the same thing. I love that guy.',
      'The sea-salt latte was an accident. The best things usually are.',
    ],
    warm: [
      'I wrote a little tune about you. It’s mostly humming right now, but it’s got heart.',
      'You’re good people, {name}. The cove’s lucky to have you.',
      'Wanna know a secret? I’m scared of seagulls. They know too much.',
    ],
    morning: ['Morning, sunshine! First cup’s on me — as soon as I finish mine.'],
    evening: ['Time for music! Pull up a bench.'],
    night: ['Late-night crowd’s the best crowd. Small, but they tip in stories.'],
    rain: ['Rainy day playlist: slow jazz and the sound of the espresso machine.'],
    gift: {
      love: 'NO WAY. You get me. You totally get me!',
      like: 'Oh nice, thanks friend!',
      neutral: 'Ha, thanks!',
      hate: 'Oh… oh, that’s a turnip. I have a complicated history with turnips.',
    },
  },
  wren: {
    intro: [
      ['surprised', 'Oh! Sorry, I didn’t hear you… I was just, um. Looking at the meadow.'],
      ['neutral', 'I’m Wren. I paint. Well — I used to. I haven’t been able to reach my spot since the bridge broke.'],
    ],
    pool: [
      'The meadow across the river turns gold in the evening. I miss painting it.',
      'Colors are just feelings you can see. Blue is my favorite. Or maybe yellow. It changes.',
      'Sorry, I’m not great at talking. I’m better at… painting what I mean.',
      'I sketch the beach sometimes. The waves never hold still. It’s rude, but beautiful.',
      'Mabel lets me borrow art books. She says I’m her best customer. I think I’m her only customer.',
      'I made my own paints once, from flowers. Poppies for red, bluebells for blue…',
    ],
    warm: [
      'I like when you visit. You don’t make me feel like I have to fill the silence.',
      'I drew you. Don’t look! …Okay you can look. It’s not finished.',
      'Thank you for being patient with me. It means more than you know.',
    ],
    morning: ['Morning light is the kindest light. It forgives every mistake in a painting.'],
    evening: ['This is the hour for painting. Everything glows.'],
    night: ['I should go home. The dark makes everything the same color.'],
    rain: ['Rain makes the colors deeper. Everything looks freshly painted.'],
    gift: {
      love: 'Oh… oh, it’s perfect. I… thank you. I’ll treasure it.',
      like: 'That’s really kind. Thank you.',
      neutral: 'Oh, thank you.',
      hate: 'Oh… um… it’s a fish. That’s… a fish.',
    },
  },
};

Object.assign(LINES, {
  bram: {
    intro: [
      ['happy', 'Well hello there! Mind the chickens, they think they own the path. They’re not wrong.'],
      ['neutral', 'Name’s Bram. I keep Honeydew Fields — the wheat, the bees, one very dramatic cow called Buttercup. You must be June’s grandkid!'],
    ],
    pool: [
      'Buttercup mooed at the moon for an hour last night. I think she’s in love with it.',
      'Wheat’s coming in golden this year. You can hear it whisper if you stand real still.',
      'The windmill’s been stuck since before the storm. Bread tastes better when you grind your own, you know.',
      'I talk to the bees every morning. Tell ’em the news. It’s an old custom — keeps ’em happy.',
      'My farm stand opens in the afternoon. Eggs, milk, honey — all of it made by friends with feathers, hooves or wings.',
      'Nana June used to buy a jar of honey every Sunday. Said it was for the tea. It was not for the tea.',
      'The sheep in the pasture are called Cloud, Biscuit, Duchess, Pudding and Little Dot. Mabel knits with their wool.',
    ],
    warm: [
      'You’ve got good hands for farming. Patient ones. Plants can tell, you know.',
      'I set a jar of honey aside for you. Don’t tell Pip, he’d eat it with a spoon.',
      'It gets quiet out here past the fields. Nice having a friend who wanders by.',
    ],
    morning: ['Up with the rooster! Well, after the rooster. The rooster is very early.'],
    evening: ['Best time of day on a farm — chores are done and the sky goes all peachy.'],
    night: ['Shh — the hens are asleep. If you wake ’em, they’ll gossip till dawn.'],
    rain: ['Rain! The wheat’s been praying for this. So have I, truth be told.'],
    gift: {
      love: 'Oh, now that’s just about the kindest thing. You’ve made a farmer’s whole week!',
      like: 'Well, isn’t that nice. Thank you kindly!',
      neutral: 'Thank you! I’ll find a good use for it.',
      hate: 'Oh. Hm. I think the chickens might like it more than me.',
    },
  },
  juniper: {
    intro: [
      ['surprised', 'Oh! Hi! Sorry — I was counting woodpeckers. I lost count. Twice.'],
      ['happy', 'I’m Juniper, the Whisperwood ranger. I look after the trails, the critters, and anyone who gets a bit lost. You’re new!'],
    ],
    pool: [
      'The old oak up the trail is over five hundred years old. Ring the shrine bell — it likes the company.',
      'There’s a grove across the river where the mushrooms glow teal at night. Glowcaps! Best thing in the valley.',
      'If you hear something rustling in the ferns, it’s probably a hedgehog. Probably.',
      'The waterfall’s loudest in spring. You can feel it in your chest standing on the shore.',
      'I sleep in a tent most nights. The stars are my ceiling and the owls are my alarm clock.',
      'Leave only footprints, take only… well, mushrooms. Some mushrooms. Not all the mushrooms.',
      'Up on Frostpine Ridge the pond freezes solid. Best slide in the valley. Don’t tell the ducks.',
      'Maple Hollow in autumn colours is my favourite place in the world. The leaf piles are there for jumping. Scientifically.',
      'Out in Reedmarsh there’s a heron who stands so still I once said hello to him for ten minutes before he blinked.',
    ],
    warm: [
      'You’re a natural out here. The forest gets quieter around people who listen.',
      'I saved you the best log by the fire. The one without the ants.',
      'Want to know a secret? I was scared of the dark as a kid. Now it’s my favorite time.',
    ],
    morning: ['Morning! Dew’s still on the ferns. Everything smells like a fresh start.'],
    evening: ['Fire’s going soon. Marshmallows are mandatory.'],
    night: ['Listen — hear that? A tawny owl. They’re asking “who-who” is still awake.'],
    rain: ['Rain in the forest is the best sound in the world. The whole Whisperwood drinks it in.'],
    gift: {
      love: 'Oh wow — for me? This is going straight in my field journal. With a heart next to it!',
      like: 'Nice find! Thanks, trail buddy.',
      neutral: 'Thanks! Every bit of the forest is worth something.',
      hate: 'Ah… I’ll, um, return this to nature. Gently.',
    },
  },
  marlo: {
    intro: [
      ['neutral', 'Ahoy there. You’ve got the look of someone who’s never been seasick. We’ll fix that.'],
      ['happy', 'Captain Marlo. I’ve run the ferry to Turtle Isle for forty-one years. The sea and I have an understanding: I don’t complain, and it doesn’t sink me.'],
    ],
    pool: [
      'When Old Glimmer went dark, I sailed by the stars. Stars don’t crack in storms.',
      'Turtle Isle’s got the best tide pools in the valley. Mind the crabs — they’re territorial and very small.',
      'I used to send letters in bottles to my sister across the bay. We were terrible spellers and wonderful sisters.',
      'The sea’s a moody old thing. Some days it sings, some days it grumbles. Today it’s humming.',
      'Ferry runs eight till seven. After that, the boat and I both need our beauty sleep.',
      'Nothing better than a mug of something hot and a horizon with nothing on it.',
    ],
    warm: [
      'You’re good company on a crossing. Most folks just stare at the water and turn green.',
      'I’ve got a spare hammock in the hut if you ever need one. It only creaks a bit.',
      'My sister would have liked you. She liked anyone who laughed at my jokes.',
    ],
    morning: ['Morning tide’s the gentlest. The sea’s still yawning.'],
    evening: ['Look at that sunset. Forty-one years and it still shows off for me.'],
    night: ['Stars are out. Every one of ’em a lighthouse, if you know how to read ’em.'],
    rain: ['A bit of rain never stopped a ferry. Grab a railing and enjoy it.'],
    gift: {
      love: 'Well, shiver my timbers — that’s a proper treasure. Thank you, sailor.',
      like: 'Kind of you. I’ll put it on the shelf with the other good things.',
      neutral: 'Thank you, dear. Every gift’s a small harbor.',
      hate: 'Hm. I’ll use it as ballast.',
    },
  },
});

export const GIFT_EXPR = { love: 'love', like: 'happy', neutral: 'neutral', hate: 'sad' };
